#!/bin/bash

names=(
  accumulate
  acronym
  affine-cipher
  allergies
  all-your-base
  alphametics
  anagram
  armstrong-numbers
  atbash-cipher
  bank-account
  basketball-website
  beer-song
  binary
  binary-search
  binary-search-tree
  bird-count
  bob
  book-store
  boutique-inventory
  boutique-suggestions
  bowling
  bread-and-potions
  captains-log
  change
  chessboard
  circular-buffer
  city-office
  clock
  collatz-conjecture
  community-garden
  complex-numbers
  connect
  crypto-square
  custom-set
  darts
  date-parser
  diamond
  difference-of-squares
  diffie-hellman
  dna-encoding
  dnd-character
  dominoes
  dot-dsl
  etl
  file-sniffer
  flatten-array
  food-chain
  forth
  freelancer-rates
  german-sysadmin
  gigasecond
  go-counting
  grade-school
  grains
  grep
  guessing-game
  hamming
  hello-world
  hexadecimal
  high-school-sweetheart
  high-score
  house
  isbn-verifier
  isogram
  kindergarten-garden
  kitchen-calculator
  knapsack
  language-list
  largest-series-product
  lasagna
  leap
  library-fees
  list-ops
  log-level
  lucas-numbers
  luhn
  markdown
  matching-brackets
  matrix
  meetup
  minesweeper
  name-badge
  need-for-speed
  newsletter
  nth-prime
  nucleotide-count
  ocr-numbers
  pacman-rules
  palindrome-products
  pangram
  parallel-letter-frequency
  pascals-triangle
  perfect-numbers
  phone-number
  pig-latin
  poker
  pov
  prime-factors
  protein-translation
  proverb
  pythagorean-triplet
  queen-attack
  rail-fence-cipher
  raindrops
  rational-numbers
  react
  rectangles
  remote-control-car
  resistor-color
  resistor-color-duo
  resistor-color-trio
  rna-transcription
  robot-simulator
  roman-numerals
  rotational-cipher
  rpg-character-sheet
  rpn-calculator
  rpn-calculator-inspection
  run-length-encoding
  saddle-points
  satellite
  say
  scale-generator
  scrabble-score
  secret-handshake
  secrets
  series
  sgf-parsing
  sieve
  simple-cipher
  simple-linked-list
  space-age
  spiral-matrix
  square-root
  stack-underflow
  strain
  sublist
  sum-of-multiples
  take-a-number
  tournament
  transpose
  triangle
  twelve-days
  two-bucket
  two-fer
  variable-length-quantity
  wine-cellar
  word-count
  word-search
  wordy
  yacht
  zebra-puzzle
  zipper
)

for name in "${names[@]}"
do
  exercism download --exercise=$name --track=elixir
done

