#!/bin/sh

exercism download --track=elixir --exercise=accumulate
exercism download --track=elixir --exercise=acronym
exercism download --track=elixir --exercise=all-your-base
exercism download --track=elixir --exercise=allergies
exercism download --track=elixir --exercise=alphametics
exercism download --track=elixir --exercise=anagram
exercism download --track=elixir --exercise=armstrong-numbers
exercism download --track=elixir --exercise=atbash-cipher
exercism download --track=elixir --exercise=bank-account
exercism download --track=elixir --exercise=beer-song
exercism download --track=elixir --exercise=binary-search-tree
exercism download --track=elixir --exercise=binary-search
exercism download --track=elixir --exercise=binary
exercism download --track=elixir --exercise=bob
exercism download --track=elixir --exercise=bowling
exercism download --track=elixir --exercise=bracket-push
exercism download --track=elixir --exercise=change
exercism download --track=elixir --exercise=clock
exercism download --track=elixir --exercise=collatz-conjecture
exercism download --track=elixir --exercise=connect
exercism download --track=elixir --exercise=crypto-square
exercism download --track=elixir --exercise=custom-set
exercism download --track=elixir --exercise=diamond
exercism download --track=elixir --exercise=difference-of-squares
exercism download --track=elixir --exercise=diffie-hellman
exercism download --track=elixir --exercise=dominoes
exercism download --track=elixir --exercise=dot-dsl
exercism download --track=elixir --exercise=etl
exercism download --track=elixir --exercise=flatten-array
exercism download --track=elixir --exercise=forth
exercism download --track=elixir --exercise=gigasecond
exercism download --track=elixir --exercise=grade-school
exercism download --track=elixir --exercise=grains
exercism download --track=elixir --exercise=grep
exercism download --track=elixir --exercise=hamming
exercism download --track=elixir --exercise=hello-world
exercism download --track=elixir --exercise=hexadecimal
exercism download --track=elixir --exercise=isbn-verifier
exercism download --track=elixir --exercise=isogram
exercism download --track=elixir --exercise=kindergarten-garden
exercism download --track=elixir --exercise=largest-series-product
exercism download --track=elixir --exercise=leap
exercism download --track=elixir --exercise=list-ops
exercism download --track=elixir --exercise=luhn
exercism download --track=elixir --exercise=markdown
exercism download --track=elixir --exercise=matrix
exercism download --track=elixir --exercise=meetup
exercism download --track=elixir --exercise=minesweeper
exercism download --track=elixir --exercise=nth-prime
exercism download --track=elixir --exercise=nucleotide-count
exercism download --track=elixir --exercise=ocr-numbers
exercism download --track=elixir --exercise=palindrome-products
exercism download --track=elixir --exercise=pangram
exercism download --track=elixir --exercise=parallel-letter-frequency
exercism download --track=elixir --exercise=pascals-triangle
exercism download --track=elixir --exercise=perfect-numbers
exercism download --track=elixir --exercise=phone-number
exercism download --track=elixir --exercise=pig-latin
exercism download --track=elixir --exercise=poker
exercism download --track=elixir --exercise=prime-factors
exercism download --track=elixir --exercise=protein-translation
exercism download --track=elixir --exercise=pythagorean-triplet
exercism download --track=elixir --exercise=queen-attack
exercism download --track=elixir --exercise=rail-fence-cipher
exercism download --track=elixir --exercise=raindrops
exercism download --track=elixir --exercise=rna-transcription
exercism download --track=elixir --exercise=robot-simulator
exercism download --track=elixir --exercise=roman-numerals
exercism download --track=elixir --exercise=rotational-cipher
exercism download --track=elixir --exercise=run-length-encoding
exercism download --track=elixir --exercise=saddle-points
exercism download --track=elixir --exercise=say
exercism download --track=elixir --exercise=scale-generator
exercism download --track=elixir --exercise=scrabble-score
exercism download --track=elixir --exercise=secret-handshake
exercism download --track=elixir --exercise=series
exercism download --track=elixir --exercise=sieve
exercism download --track=elixir --exercise=simple-cipher
exercism download --track=elixir --exercise=simple-linked-list
exercism download --track=elixir --exercise=space-age
exercism download --track=elixir --exercise=spiral-matrix
exercism download --track=elixir --exercise=strain
exercism download --track=elixir --exercise=sublist
exercism download --track=elixir --exercise=sum-of-multiples
exercism download --track=elixir --exercise=tournament
exercism download --track=elixir --exercise=transpose
exercism download --track=elixir --exercise=triangle
exercism download --track=elixir --exercise=twelve-days
exercism download --track=elixir --exercise=two-for
exercism download --track=elixir --exercise=word-count
exercism download --track=elixir --exercise=wordy
exercism download --track=elixir --exercise=zipper
