#!/bin/sh

exercism download --track=common-lisp --exercise=acronym
exercism download --track=common-lisp --exercise=all-your-base
exercism download --track=common-lisp --exercise=allergies
exercism download --track=common-lisp --exercise=anagram
exercism download --track=common-lisp --exercise=armstrong-numbers
exercism download --track=common-lisp --exercise=atbash-cipher
exercism download --track=common-lisp --exercise=beer-song
exercism download --track=common-lisp --exercise=binary
exercism download --track=common-lisp --exercise=bob
exercism download --track=common-lisp --exercise=collatz-conjecture
exercism download --track=common-lisp --exercise=crypto-square
exercism download --track=common-lisp --exercise=difference-of-squares
exercism download --track=common-lisp --exercise=etl
exercism download --track=common-lisp --exercise=gigasecond
exercism download --track=common-lisp --exercise=grade-school
exercism download --track=common-lisp --exercise=grains
exercism download --track=common-lisp --exercise=hamming
exercism download --track=common-lisp --exercise=hello-world
exercism download --track=common-lisp --exercise=isogram
exercism download --track=common-lisp --exercise=leap
exercism download --track=common-lisp --exercise=luhn
exercism download --track=common-lisp --exercise=meetup
exercism download --track=common-lisp --exercise=nucleotide-count
exercism download --track=common-lisp --exercise=pascals-triangle
exercism download --track=common-lisp --exercise=perfect-numbers
exercism download --track=common-lisp --exercise=phone-number
exercism download --track=common-lisp --exercise=prime-factors
exercism download --track=common-lisp --exercise=raindrops
exercism download --track=common-lisp --exercise=rna-transcription
exercism download --track=common-lisp --exercise=robot-name
exercism download --track=common-lisp --exercise=robot-simulator
exercism download --track=common-lisp --exercise=roman-numerals
exercism download --track=common-lisp --exercise=scrabble-score
exercism download --track=common-lisp --exercise=sieve
exercism download --track=common-lisp --exercise=space-age
exercism download --track=common-lisp --exercise=strain
exercism download --track=common-lisp --exercise=sublist
exercism download --track=common-lisp --exercise=trinary
exercism download --track=common-lisp --exercise=twelve-days
exercism download --track=common-lisp --exercise=two-fer
exercism download --track=common-lisp --exercise=word-count
