#!/bin/sh

exercism download --track=scheme --exercise=affine-cipher
exercism download --track=scheme --exercise=anagram
exercism download --track=scheme --exercise=atbash-cipher
exercism download --track=scheme --exercise=binary-search
exercism download --track=scheme --exercise=bob
exercism download --track=scheme --exercise=change
exercism download --track=scheme --exercise=collatz-conjecture
exercism download --track=scheme --exercise=difference-of-squares
exercism download --track=scheme --exercise=forth
exercism download --track=scheme --exercise=grains
exercism download --track=scheme --exercise=hamming
exercism download --track=scheme --exercise=hello-world
exercism download --track=scheme --exercise=knapsack
exercism download --track=scheme --exercise=leap
exercism download --track=scheme --exercise=matching-brackets
exercism download --track=scheme --exercise=nucleotide-count
exercism download --track=scheme --exercise=pangram
exercism download --track=scheme --exercise=pascals-triangle
exercism download --track=scheme --exercise=perfect-numbers
exercism download --track=scheme --exercise=phone-number
exercism download --track=scheme --exercise=prime-factors
exercism download --track=scheme --exercise=queen-attack
exercism download --track=scheme --exercise=raindrops
exercism download --track=scheme --exercise=rna-transcription
exercism download --track=scheme --exercise=rotational-cipher
exercism download --track=scheme --exercise=scrabble-score
exercism download --track=scheme --exercise=sieve
exercism download --track=scheme --exercise=transpose
exercism download --track=scheme --exercise=two-fer
exercism download --track=scheme --exercise=word-count
