#!/bin/bash

names=(
  acronym
  all-your-base
  allergies
  anagram
  armstrong-numbers
  atbash-cipher
  beer-song
  binary
  binary-search
  bob
  character-study
  collatz-conjecture
  crypto-square
  difference-of-squares
  etl
  gigasecond
  gigasecond-anniversary
  grade-school
  grains
  hamming
  hello-world
  high-scores
  isogram
  key-comparison
  larrys-winning-checker
  leap
  leslies-lists
  lillys-lasagna
  lillys-lasagna-leftovers
  log-levels
  lucys-magnificent-mapper
  luhn
  meetup
  nucleotide-count
  pal-picker
  pascals-triangle
  perfect-numbers
  phone-number
  pizza-pi
  prime-factors
  raindrops
  rna-transcription
  robot-name
  robot-simulator
  roman-numerals
  scrabble-score
  sieve
  socks-and-sexprs
  space-age
  strain
  sublist
  triangle
  trinary
  twelve-days
  two-fer
  word-count
)

for name in "${names[@]}"
do
  exercism download --exercise=$name --track=common-lisp
done
